{
 "title": "Heizung (Modbus)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(isg_istwert_hk1) or max(isg_istwert{hk=\"1\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Ist",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_sollwert_hk1) or max(isg_sollwert{hk=\"1\"})",
     "legendFormat": "Soll"
    },
    { "expr": "max(isg_vorlauftemp) ", "legendFormat": "Vorlauf" },
    { "expr": "max(isg_ruecklauftemp) ", "legendFormat": "Rücklauf" },
    { "expr": "max(isg_ww_isttemp)", "legendFormat": "WW Ist" },
    { "expr": "max(isg_ww_solltemp)", "legendFormat": "WW Soll" },
    { "expr": "max(isg_aussentemperatur)", "legendFormat": "Außentemperatur" }
   ]
  },
  {
   "title": "Wärmepumpe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(isg_verdampfertemp)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Verdampfer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "max(isg_verfluessigertemp)", "legendFormat": "Verflüssiger" },
    { "expr": "max(isg_niederdruck)", "legendFormat": "Niederdruck" },
    { "expr": "max(isg_hochdruck)", "legendFormat": "Hochdruck" },
    { "expr": "max(isg_heissgastemp)", "legendFormat": "Heißgas" },
    { "expr": "max(isg_druck_heizkreis)", "legendFormat": "Druck Heizkreis" },
    { "expr": "max(isg_nd_gefiltert)", "legendFormat": "Niederdruck gefiltert" },
    { "expr": "max(isg_verdampferausg_temp)", "legendFormat": "Verdampferausgang" },
    { "expr": "max(isg_kuehlungstemp)", "legendFormat": "Kühlungstemperatur" }
   ]
  },
  {
   "title": "Volumenstrom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    { "expr": "max(isg_volumenstrom)", "legendFormat": "Volumenstrom" }
   ]
  },
  {
   "title": "Flags",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(isg_flag_abtauen_ll_wt)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Abtauen LL WT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_flag_abtauen_verdampfer)",
     "legendFormat": "Abtauen Verdampfer"
    },
    { "expr": "max(isg_flag_heizen)", "legendFormat": "Heizen" },
    { "expr": "max(isg_flag_heizkreispumpe)", "legendFormat": "HK Pumpe" },
    {
     "expr": "max(isg_flag_warmwasserbereitung)",
     "legendFormat": "WW Bereitung"
    },
    { "expr": "max(isg_flag_evu_sperre)", "legendFormat": "EVU-Sperre" },
    { "expr": "max(isg_flag_verdichter)", "legendFormat": "Verdichter" },
    { "expr": "max(isg_flag_hd_waechter)", "legendFormat": "HD-Wächter" },
    { "expr": "max(isg_flag_luefter)", "legendFormat": "Lüfter" },
    { "expr": "max(isg_flag_stoerung)", "legendFormat": "Störung/Service" },
    { "expr": "isg_flag", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Wärmemengen / Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max(irate(isg_wm_heizen_tag[5m])*3600)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Heizen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(irate(isg_wm_ww_tag[5m])*3600)",
     "legendFormat": "Warmwasser"
    },
    {
     "expr": "max(irate(isg_wm_wrg_tag[5m])*3600)",
     "legendFormat": "Wäremerückgewinnung"
    },
    {
     "expr": "max(irate(isg_wm_ne_heizen_summe[5m])*3600)",
     "legendFormat": "NE Heizen"
    },
    {
     "expr": "max(irate(isg_wm_ne_ww_summe[5m])*3600)",
     "legendFormat": "NE Warmwasser"
    },
    {
     "expr": "max(irate(isg_p_heizung_tag[5m])*3600)",
     "legendFormat": "Leistung Heizen"
    },
    {
     "expr": "max(irate(isg_p_ww_tag[5m])*3600)",
     "legendFormat": "Leistung Warmwasser"
    },
    {
     "expr": "max(irate(isg_wm_heizen_tag[5m])) / max(irate(isg_p_heizung_tag[5m]))",
     "legendFormat": "Effizienz Heizen"
    },
    {
     "expr": "max(irate(isg_wm_ww_tag[5m])) / max(irate(isg_p_ww_tag[5m]))",
     "legendFormat": "Effizienz Warmwasser"
    }
   ]
  },
  {
   "title": "Lüfterdurchsatz (Soll)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(isg_abluft_soll_volumenstrom)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Abluft Volumen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_zuluft_soll_volumenstrom)",
     "legendFormat": "Zuluft Volumen"
    },
    {
     "expr": "max(isg_fortluft_soll_volumenstrom)",
     "legendFormat": "Fortluft Volumen"
    }
   ]
  },
  {
   "title": "Lüfterdrehzahl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max(isg_zuluft_ist_luefterdrehzahl)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Zuluft Drehzahl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_abluft_ist_luefterdrehzahl)",
     "legendFormat": "Abluft Drehzahl"
    },
    {
     "expr": "max(isg_fortluft_ist_luefterdrehzahl)",
     "legendFormat": "Fortluft Drehzahl"
    }
   ]
  }
 ]
}