{
 "title": "Heizung",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperaturen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(isg_istwert_hk1) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Ist",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "max(isg_sollwert_hk1) ", "legendFormat": "Soll" },
    { "expr": "max(isg_vorlauftemp) ", "legendFormat": "Vorlauf" },
    { "expr": "max(isg_ruecklauftemp) ", "legendFormat": "Rücklauf" },
    { "expr": "max(isg_ww_isttemp)", "legendFormat": "WW Ist" },
    { "expr": "max(isg_ww_solltemp)", "legendFormat": "WW Soll" },
    { "expr": "max(isg_aussentemperatur)", "legendFormat": "Außentemperatur" }
   ]
  },
  {
   "title": "Wärmepumpe",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(isg_verdampfertemp)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Verdampfer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "max(isg_verfluessigertemp)", "legendFormat": "Verflüssiger" },
    { "expr": "max(isg_niederdruck)", "legendFormat": "Niederdruck" },
    { "expr": "max(isg_hochdruck)", "legendFormat": "Hochdruck" },
    { "expr": "max(isg_heissgastemp)", "legendFormat": "Heißgas" }
   ]
  },
  {
   "title": "Flags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(isg_flag_abtauen_ll_wt)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Abtauen LL WT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_flag_abtauen_verdampfer)",
     "legendFormat": "Abtauen Verdampfer"
    },
    { "expr": "max(isg_flag_heizen)", "legendFormat": "Heizen" },
    { "expr": "max(isg_flag_heizkreispumpe)", "legendFormat": "HK Pumpe" },
    {
     "expr": "max(isg_flag_warmwasserbereitung)",
     "legendFormat": "WW Bereitung"
    }
   ]
  },
  {
   "title": "Heizstufen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(isg_heizstufe) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Heizstufen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "max(isg_nhz_stufen) ", "legendFormat": "Notheizstufen" }
   ]
  },
  {
   "title": "Wärmemengen / Leistung",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "kwatth", "label": "kWh/h" }
   ],
   "targets": [
    {
     "expr": "max(irate(isg_wm_heizen_tag[5m])*3600)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Heizen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(irate(isg_wm_ww_tag[5m])*3600)",
     "legendFormat": "Warmwasser"
    },
    {
     "expr": "max(irate(isg_wm_wrg_tag[5m])*3600)",
     "legendFormat": "Wäremerückgewinnung"
    },
    {
     "expr": "max(irate(isg_wm_ne_heizen_summe[5m])*3600)",
     "legendFormat": "NE Heizen"
    },
    {
     "expr": "max(irate(isg_wm_ne_ww_summe[5m])*3600)",
     "legendFormat": "NE Warmwasser"
    },
    {
     "expr": "max(irate(isg_p_heizung_tag[5m])*3600)",
     "legendFormat": "Leistung Heizen"
    },
    {
     "expr": "max(irate(isg_p_ww_tag[5m])*3600)",
     "legendFormat": "Leistung Warmwasser"
    },
    {
     "expr": "max(irate(isg_wm_heizen_tag[5m])) / max(irate(isg_p_heizung_tag[5m]))",
     "legendFormat": "Effizienz Heizen"
    },
    {
     "expr": "max(irate(isg_wm_ww_tag[5m])) / max(irate(isg_p_ww_tag[5m]))",
     "legendFormat": "Effizienz Warmwasser"
    }
   ]
  },
  {
   "title": "Lüfterdurchsatz (Soll)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "m3/h" }
   ],
   "targets": [
    {
     "expr": "max(isg_abluft_soll_volumenstrom)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Abluft Volumen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_zuluft_soll_volumenstrom)",
     "legendFormat": "Zuluft Volumen"
    },
    {
     "expr": "max(isg_fortluft_soll_volumenstrom)",
     "legendFormat": "Fortluft Volumen"
    }
   ]
  },
  {
   "title": "Lüfterdrehzahl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "max(isg_zuluft_ist_luefterdrehzahl)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Zuluft Drehzahl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(isg_abluft_ist_luefterdrehzahl)",
     "legendFormat": "Abluft Drehzahl"
    },
    {
     "expr": "max(isg_fortluft_ist_luefterdrehzahl)",
     "legendFormat": "Fortluft Drehzahl"
    }
   ]
  }
 ]
}