name: Docker Build/Publish Image on PR
on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main
jobs:
  build:
    uses: sfudeus/workflows/.github/workflows/docker-build-publish-pr.yaml@main
    secrets: inherit
    with:
      tag: preview-${{ github.event.number }}
