name: Docker Build/Publish Image
on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GO_VERSION: 1.15.6
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Define revision
      id: revision
      run: |
        git fetch --tags --unshallow
        REVISION=$(git describe --tags --dirty)
        echo "::set-output name=target-revision::$REVISION"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build/push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
        tags: "sfudeus/isg_exporter:${{ steps.revision.outputs.target-revision }}"
        push: true
