name: Docker Build/Publish Release
on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Define revision
      id: revision
      run: |
        git fetch --tags --unshallow
        REVISION=$(git describe --tags --dirty)
        echo "target-revision=$REVISION" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build/push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: |
          "${{ github.repository }}:${{ steps.revision.outputs.target-revision }}"
          "${{ github.repository }}:latest"
        push: true
    - name: Comment docker repo
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Release published at docker.io/' + "${{ github.repository }}:${{ steps.revision.outputs.target-revision }}"
          })